"use client";
import { createContext, useContext, useState, useEffect } from "react";

const UI = {
  he: {
    loading: "טוען…",
    logout: "התנתק",
    switch_lang: "🇬🇧 English",
    level_label: "רמת לימוד",
    level_short: "רמה",
    hero_greeting: "בונז'ור",
    hero_ready: "מוכן לאתגר {level}?",
    hero_practiced_today: "כבר התאמנת היום ברמה {level} — עוד סבב?",
    start_challenge: "התחל אתגר",
    stat_streak: "ימים רצוף",
    stat_xp: "XP כולל",
    stat_correct: "תשובות נכונות",
    progress_eyebrow: "ההתקדמות שלך",
    map_paris: "פריז",
    map_lines: "קווים",
    progress_title: "המסע שלך ברמה {level} — תחנה לכל 3 תשובות נכונות",
    station: "תחנה",
    this_week: "השבוע",
    weekly_xp_title: "XP ב-7 הימים האחרונים",
    daily_challenge: "אתגר יומי",
    rounds: "סבבים",
    round: "סבב",
    intro_desc: "ארבעה סבבים. הקש על 🔊 לשמוע צרפתית, ועל «תרגום» לראות עברית. תשובה נכונה: +50 XP · שגויה: −15 XP עם הסבר מלא.",
    streak_banner: "רצף של {streak} ימים — אל תשבור אותו! השלם אתגר היום.",
    placeholder_open: "כתוב את תשובתך בצרפתית...",
    placeholder_answer: "התשובה שלך בצרפתית...",
    checking: "Claude בודק…",
    check_my_answer: "בדוק את התשובה שלי",
    show_model: "הצג תשובת מודל",
    submit_answer: "שלח תשובה",
    fb_excellent: "מצוין! 🎉",
    fb_good: "טוב — עם תיקונים",
    fb_needs_work: "צריך עבודה",
    fb_model: "תשובת מודל",
    fb_correct: "✓ נכון!",
    fb_wrong: "✗ טעות",
    tip: "טיפ",
    finish_challenge: "סיים אתגר 🎉",
    next_round: "הסבב הבא ←",
    done_streak: "רצף של {streak} ימים — כל הכבוד! 🔥",
    done_first_streak: "סיימת את האתגר היומי. הסטריק התחיל! 🔥",
    session_xp: "XP בסשן הזה",
    total: "סה״כ",
    another_challenge: "אתגר נוסף",
    home: "דף הבית",
    welcome: "ברוך הבא",
    name_prompt: "איך קוראים לך?",
    name_placeholder: "שמך...",
    lets_start: "בואו נתחיל",
    change_name: "שנה שם",
    translation: "תרגום",
    hide_translation: "הסתר תרגום",
    music_off: "כבה מוזיקת רקע",
    music_on: "הפעל מוזיקת רקע",
    choose_melody: "בחר מנגינה",
    home_tab: "בית",
    lessons_tab: "שיעורים",
    lessons_coming_soon: "בקרוב...",
    lessons_examples: "דוגמאות",
    lessons_vocab: "אוצר מילים",
    lessons_grammar: "דקדוק",
    /* auth */
    auth_tagline: "למד צרפתית כמו פריזאי אמיתי",
    auth_login: "התחברות",
    auth_signup: "הרשמה",
    auth_reset_desc: "הכנס את כתובת האימייל שלך ונשלח לך קישור לאיפוס הסיסמה.",
    auth_email: "אימייל",
    auth_password: "סיסמה",
    auth_password_placeholder: "לפחות 6 תווים",
    auth_forgot_password: "שכחתי סיסמה",
    auth_login_btn: "התחבר",
    auth_signup_btn: "צור חשבון",
    auth_send_reset: "שלח קישור לאיפוס",
    auth_back_to_login: "חזרה להתחברות",
    auth_google: "המשך עם Google",
    auth_or: "או",
    auth_no_account: "אין לך חשבון?",
    auth_have_account: "כבר רשום?",
    auth_signup_link: "הירשם עכשיו",
    auth_login_link: "התחבר",
    auth_signup_success: "נשלח מייל אימות — בדוק את תיבת הדואר שלך ולחץ על הקישור.",
    auth_reset_success: "נשלח מייל לאיפוס הסיסמה — בדוק את תיבת הדואר שלך.",
    auth_err_invalid: "אימייל או סיסמה שגויים.",
    auth_err_unconfirmed: "יש לאמת את האימייל תחילה — בדוק את תיבת הדואר.",
    auth_err_registered: "כתובת אימייל זו כבר רשומה. נסה להתחבר.",
    auth_err_weak_password: "הסיסמה חייבת להכיל לפחות 6 תווים.",
    auth_err_generic: "אירעה שגיאה, נסה שוב.",
  },
  en: {
    loading: "Loading…",
    logout: "Log out",
    switch_lang: "🇮🇱 עברית",
    level_label: "Study level",
    level_short: "Level",
    hero_greeting: "Bonjour",
    hero_ready: "Ready for the {level} challenge?",
    hero_practiced_today: "Already practiced {level} today — another round?",
    start_challenge: "Start challenge",
    stat_streak: "day streak",
    stat_xp: "total XP",
    stat_correct: "correct answers",
    progress_eyebrow: "Your progress",
    map_paris: "Paris",
    map_lines: "Lines",
    progress_title: "Your {level} journey — one station per 3 correct answers",
    station: "Station",
    this_week: "This week",
    weekly_xp_title: "XP earned in the last 7 days",
    daily_challenge: "Daily challenge",
    rounds: "rounds",
    round: "Round",
    intro_desc: "Four rounds. Tap 🔊 to hear French, and «Translation» to see English. Correct: +50 XP · Wrong: −15 XP with full explanation.",
    streak_banner: "{streak}-day streak — don't break it! Complete today's challenge.",
    placeholder_open: "Write your answer in French...",
    placeholder_answer: "Your answer in French...",
    checking: "Claude is checking…",
    check_my_answer: "Check my answer",
    show_model: "Show model answer",
    submit_answer: "Submit answer",
    fb_excellent: "Excellent! 🎉",
    fb_good: "Good — with corrections",
    fb_needs_work: "Needs work",
    fb_model: "Model answer",
    fb_correct: "✓ Correct!",
    fb_wrong: "✗ Incorrect",
    tip: "Tip",
    finish_challenge: "Finish challenge 🎉",
    next_round: "Next round →",
    done_streak: "{streak}-day streak — well done! 🔥",
    done_first_streak: "You completed today's challenge. Streak started! 🔥",
    session_xp: "XP this session",
    total: "total",
    another_challenge: "Another round",
    home: "Home",
    welcome: "Welcome",
    name_prompt: "What's your name?",
    name_placeholder: "Your name...",
    lets_start: "Let's start",
    change_name: "Change name",
    translation: "Translation",
    hide_translation: "Hide translation",
    music_off: "Turn off background music",
    music_on: "Turn on background music",
    choose_melody: "Choose melody",
    home_tab: "Home",
    lessons_tab: "Lessons",
    lessons_coming_soon: "Coming soon...",
    lessons_examples: "Examples",
    lessons_vocab: "Vocabulary",
    lessons_grammar: "Grammar",
    /* auth */
    auth_tagline: "Learn French like a true Parisian",
    auth_login: "Log in",
    auth_signup: "Sign up",
    auth_reset_desc: "Enter your email address and we'll send you a password reset link.",
    auth_email: "Email",
    auth_password: "Password",
    auth_password_placeholder: "At least 6 characters",
    auth_forgot_password: "Forgot password",
    auth_login_btn: "Log in",
    auth_signup_btn: "Create account",
    auth_send_reset: "Send reset link",
    auth_back_to_login: "Back to login",
    auth_google: "Continue with Google",
    auth_or: "or",
    auth_no_account: "Don't have an account?",
    auth_have_account: "Already registered?",
    auth_signup_link: "Sign up now",
    auth_login_link: "Log in",
    auth_signup_success: "Verification email sent — check your inbox and click the link.",
    auth_reset_success: "Password reset email sent — check your inbox.",
    auth_err_invalid: "Incorrect email or password.",
    auth_err_unconfirmed: "Please confirm your email first — check your inbox.",
    auth_err_registered: "This email is already registered. Try logging in.",
    auth_err_weak_password: "Password must be at least 6 characters.",
    auth_err_generic: "An error occurred, please try again.",
  },
};

export const LangContext = createContext({ lang: "he", setLang: () => {}, ui: UI.he });

export function LangProvider({ children }) {
  const [lang, setLangState] = useState("he");
  useEffect(() => {
    const saved = typeof window !== "undefined" && localStorage.getItem("frenchup_lang");
    if (saved === "en" || saved === "he") setLangState(saved);
  }, []);
  const setLang = (l) => {
    setLangState(l);
    if (typeof window !== "undefined") localStorage.setItem("frenchup_lang", l);
  };
  return <LangContext.Provider value={{ lang, setLang, ui: UI[lang] }}>{children}</LangContext.Provider>;
}

export function useLang() { return useContext(LangContext); }
