const LESSONS = {
  A1: [
    {
      id: "A1_L1",
      title_he: "כינויי גוף + être",
      title_en: "Personal pronouns + être",
      title_fr: "Pronoms personnels & être",
      theory_he: "בצרפתית, כל פועל מוטה בהתאם לכינוי הגוף. הפועל être (להיות) הוא אחד הפעלים הבסיסיים ביותר. למד את הטיות שלו בעל-פה — הן מופיעות בכל משפט.",
      theory_en: "In French, every verb is conjugated according to its subject pronoun. The verb être (to be) is one of the most fundamental verbs. Learn its conjugations by heart — they appear in every sentence.",
      grammar: {
        headers: ["Pronom", "être", "Exemple"],
        rows: [
          ["je", "suis", "Je suis étudiant(e)."],
          ["tu", "es", "Tu es français(e)."],
          ["il/elle", "est", "Elle est médecin."],
          ["nous", "sommes", "Nous sommes amis."],
          ["vous", "êtes", "Vous êtes professeur."],
          ["ils/elles", "sont", "Ils sont contents."],
        ],
      },
      vocab: [
        { fr: "je suis", he: "אני הוא/היא", en: "I am" },
        { fr: "tu es", he: "אתה/את הוא/היא", en: "you are" },
        { fr: "il est", he: "הוא הוא", en: "he is" },
        { fr: "elle est", he: "היא היא", en: "she is" },
        { fr: "nous sommes", he: "אנחנו", en: "we are" },
        { fr: "vous êtes", he: "אתם / הינכם (פורמלי)", en: "you are (pl/formal)" },
        { fr: "ils sont", he: "הם", en: "they are (m)" },
      ],
      examples: [
        { fr: "Je suis étudiant.", he: "אני סטודנט.", en: "I am a student." },
        { fr: "Elle est française.", he: "היא צרפתייה.", en: "She is French." },
        { fr: "Nous sommes amis.", he: "אנחנו חברים.", en: "We are friends." },
        { fr: "Vous êtes professeur ?", he: "אתה מורה?", en: "Are you a teacher?" },
      ],
      video: "XVWImVHQkk0",
      images: [
        {
          url: "https://images.unsplash.com/photo-1431274172761-fca41d930114?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "פריז — עיר השפה הצרפתית",
          caption_en: "Paris — home of the French language",
          type: "illustration",
        },
      ],
    },
    {
      id: "A1_L2",
      title_he: "שלילה: ne…pas",
      title_en: "Negation: ne…pas",
      title_fr: "La négation: ne…pas",
      theory_he: "כדי לשלול משפט בצרפתית, עוטפים את הפועל ב-ne…pas. בדיבור מהיר, ה-ne לעיתים נשמט. חשוב להכיר את שתי הצורות.",
      theory_en: "To negate a sentence in French, wrap the verb with ne…pas. In fast speech, the ne is often dropped. It is important to recognize both forms.",
      grammar: {
        headers: ["חיובי", "שלילי"],
        rows: [
          ["Je suis français.", "Je ne suis pas français."],
          ["Tu parles anglais.", "Tu ne parles pas anglais."],
          ["Il est médecin.", "Il n'est pas médecin."],
          ["Nous sommes là.", "Nous ne sommes pas là."],
        ],
      },
      vocab: [
        { fr: "ne … pas", he: "לא (שלילה)", en: "not (negation)" },
        { fr: "jamais", he: "אף פעם", en: "never" },
        { fr: "plus", he: "לא יותר", en: "no longer" },
        { fr: "rien", he: "כלום", en: "nothing" },
        { fr: "personne", he: "אף אחד", en: "nobody" },
      ],
      examples: [
        { fr: "Je ne suis pas français.", he: "אני לא צרפתי.", en: "I am not French." },
        { fr: "Il n'est pas là.", he: "הוא לא פה.", en: "He is not here." },
        { fr: "Elle ne parle pas anglais.", he: "היא לא מדברת אנגלית.", en: "She does not speak English." },
        { fr: "Je ne comprends pas.", he: "אני לא מבין.", en: "I don't understand." },
      ],
      video: "Lz4U1xTJPfY",
      images: [
        {
          url: "https://images.unsplash.com/photo-1772119044027-04e80adeda6b?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "שיחה יומיומית בצרפתית — ne…pas בפעולה",
          caption_en: "Everyday French conversation — ne…pas in action",
          type: "illustration",
        },
      ],
    },
    {
      id: "A1_L3",
      title_he: "המין הדקדוקי: זכר ונקבה",
      title_en: "Grammatical gender: masculine & feminine",
      title_fr: "Le genre grammatical",
      theory_he: "כל שם עצם בצרפתית הוא זכר או נקבה. אין חוק קבוע, אך יש סיומות שמסגירות את המין. לנקבה מוסיפים בדרך כלל -e, ולתואר חשוב להתאים.",
      theory_en: "Every noun in French is either masculine or feminine. There is no fixed rule, but certain endings hint at the gender. Feminine nouns usually add -e, and adjectives must agree.",
      grammar: {
        headers: ["זכר (Masculin)", "נקבה (Féminin)", "משמעות"],
        rows: [
          ["un ami", "une amie", "חבר / חברה"],
          ["un étudiant", "une étudiante", "סטודנט / סטודנטית"],
          ["le livre", "la table", "ספר / שולחן"],
          ["beau", "belle", "יפה"],
          ["grand", "grande", "גדול / גדולה"],
        ],
      },
      vocab: [
        { fr: "le / un", he: "ה / יצ' (זכר)", en: "the / a (masc.)" },
        { fr: "la / une", he: "ה / יצ' (נקבה)", en: "the / a (fem.)" },
        { fr: "les / des", he: "הרבים / כמה", en: "the (pl.) / some" },
        { fr: "masculin", he: "זכר", en: "masculine" },
        { fr: "féminin", he: "נקבה", en: "feminine" },
      ],
      examples: [
        { fr: "Un ami et une amie.", he: "חבר וחברה.", en: "A (male) friend and a (female) friend." },
        { fr: "Le livre est grand.", he: "הספר גדול.", en: "The book is big." },
        { fr: "La table est belle.", he: "השולחן יפה.", en: "The table is beautiful." },
        { fr: "Des étudiants et des étudiantes.", he: "סטודנטים וסטודנטיות.", en: "Students (m) and students (f)." },
      ],
      video: "FQM0Sau7yl0",
      images: [
        {
          url: "https://images.unsplash.com/photo-1562079859-ef41b665a46d?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "הבולנז'רי — le pain (זכר), la baguette (נקבה)",
          caption_en: "The boulangerie — le pain (masc.), la baguette (fem.)",
          type: "illustration",
        },
      ],
    },
    {
      id: "A1_L4",
      title_he: "הפועל avoir — יש לי",
      title_en: "The verb avoir — to have",
      title_fr: "Le verbe avoir",
      theory_he: "הפועל avoir (יש לי / יש לך...) הכרחי: הוא מופיע בביטויי גיל, רגש, ובניית זמנים מורכבים. שים לב: בצרפתית אומרים 'יש לי X שנים' ולא 'אני בן X'.",
      theory_en: "The verb avoir (to have) is essential: it appears in expressions of age, feeling, and in compound tenses. Note: in French you say 'I have X years' rather than 'I am X years old'.",
      grammar: {
        headers: ["Pronom", "avoir", "Exemple"],
        rows: [
          ["je", "ai", "J'ai vingt ans."],
          ["tu", "as", "Tu as faim ?"],
          ["il/elle", "a", "Elle a un chat."],
          ["nous", "avons", "Nous avons une maison."],
          ["vous", "avez", "Vous avez le temps ?"],
          ["ils/elles", "ont", "Ils ont de la chance."],
        ],
      },
      vocab: [
        { fr: "avoir faim", he: "להיות רעב", en: "to be hungry" },
        { fr: "avoir soif", he: "להיות צמא", en: "to be thirsty" },
        { fr: "avoir sommeil", he: "להיות ישנוני", en: "to be sleepy" },
        { fr: "avoir peur", he: "לפחד", en: "to be afraid" },
        { fr: "avoir raison", he: "לצדוק", en: "to be right" },
        { fr: "avoir tort", he: "לטעות", en: "to be wrong" },
      ],
      examples: [
        { fr: "J'ai vingt ans.", he: "אני בן עשרים.", en: "I am twenty years old." },
        { fr: "Elle a un chat.", he: "יש לה חתול.", en: "She has a cat." },
        { fr: "Nous avons faim.", he: "אנחנו רעבים.", en: "We are hungry." },
        { fr: "Tu as raison.", he: "אתה צודק.", en: "You are right." },
      ],
      video: "oLxEv4o31M4",
      images: [
        {
          url: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "בקפה הצרפתי — avoir faim, avoir soif",
          caption_en: "At the French café — avoir faim, avoir soif",
          type: "illustration",
        },
      ],
    },
    {
      id: "A1_L5",
      title_he: "פעלי -er בהווה",
      title_en: "Regular -er verbs in the present",
      title_fr: "Les verbes en -er au présent",
      theory_he: "רוב הפעלים בצרפתית הם מקבוצת -er. מסירים את -er ומוסיפים את הסיומות: -e, -es, -e, -ons, -ez, -ent. חשוב: -ent בסוף שם לא נהגה.",
      theory_en: "Most French verbs belong to the -er group. Remove -er and add the endings: -e, -es, -e, -ons, -ez, -ent. Important: the final -ent is silent.",
      grammar: {
        headers: ["Pronom", "parler", "manger", "habiter"],
        rows: [
          ["je", "parle", "mange", "habite"],
          ["tu", "parles", "manges", "habites"],
          ["il/elle", "parle", "mange", "habite"],
          ["nous", "parlons", "mangeons", "habitons"],
          ["vous", "parlez", "mangez", "habitez"],
          ["ils/elles", "parlent", "mangent", "habitent"],
        ],
      },
      vocab: [
        { fr: "parler", he: "לדבר", en: "to speak" },
        { fr: "manger", he: "לאכול", en: "to eat" },
        { fr: "habiter", he: "לגור", en: "to live (somewhere)" },
        { fr: "travailler", he: "לעבוד", en: "to work" },
        { fr: "aimer", he: "לאהוב", en: "to love / to like" },
        { fr: "étudier", he: "ללמוד", en: "to study" },
        { fr: "voyager", he: "לטייל", en: "to travel" },
      ],
      examples: [
        { fr: "Je parle français.", he: "אני מדבר צרפתית.", en: "I speak French." },
        { fr: "Elle habite à Paris.", he: "היא גרה בפריז.", en: "She lives in Paris." },
        { fr: "Nous mangeons ensemble.", he: "אנחנו אוכלים ביחד.", en: "We eat together." },
        { fr: "Ils travaillent beaucoup.", he: "הם עובדים הרבה.", en: "They work a lot." },
      ],
      video: "5WiTJJ4N2jQ",
      images: [
        {
          url: "https://images.unsplash.com/photo-1686317508857-3b91999d6ec8?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "פריזאים בפעולה: parler, manger, habiter",
          caption_en: "Parisians in action: parler, manger, habiter",
          type: "illustration",
        },
      ],
    },
    {
      id: "A1_L6",
      title_he: "שאלות בסיסיות",
      title_en: "Basic questions",
      title_fr: "Les questions de base",
      theory_he: "בצרפתית יש שלוש דרכים לשאול שאלה: אינטונציה עולה, est-ce que + משפט, או היפוך (פועל-כינוי). בדיבור יומיומי, האינטונציה הכי נפוצה.",
      theory_en: "In French there are three ways to ask a question: rising intonation, est-ce que + sentence, or inversion (verb-pronoun). In everyday speech, rising intonation is most common.",
      grammar: {
        headers: ["סוג שאלה", "דוגמה", "תרגום"],
        rows: [
          ["אינטונציה", "Tu parles français ?", "אתה מדבר צרפתית?"],
          ["Est-ce que", "Est-ce que tu parles français ?", "האם אתה מדבר צרפתית?"],
          ["היפוך", "Parles-tu français ?", "האם אתה מדבר צרפתית? (פורמלי)"],
          ["Où", "Où habitez-vous ?", "איפה אתם גרים?"],
          ["Comment", "Comment vous appelez-vous ?", "מה שמכם?"],
          ["Quand", "Quand arrivez-vous ?", "מתי אתם מגיעים?"],
        ],
      },
      vocab: [
        { fr: "où", he: "איפה", en: "where" },
        { fr: "quand", he: "מתי", en: "when" },
        { fr: "comment", he: "איך", en: "how" },
        { fr: "pourquoi", he: "למה", en: "why" },
        { fr: "qui", he: "מי", en: "who" },
        { fr: "quoi / que", he: "מה", en: "what" },
        { fr: "combien", he: "כמה", en: "how much/many" },
      ],
      examples: [
        { fr: "Comment tu t'appelles ?", he: "מה שמך?", en: "What is your name?" },
        { fr: "Où est-ce que tu habites ?", he: "איפה אתה גר?", en: "Where do you live?" },
        { fr: "Pourquoi tu apprends le français ?", he: "למה אתה לומד צרפתית?", en: "Why are you learning French?" },
        { fr: "Combien ça coûte ?", he: "כמה זה עולה?", en: "How much does it cost?" },
      ],
      video: "Q1QwjVcAzqs",
      images: [
        {
          url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "תיירים שואלים שאלות בפריז — où, comment, combien?",
          caption_en: "Tourists asking questions in Paris — où, comment, combien?",
          type: "illustration",
        },
      ],
    },
  ],

  A2: [
    {
      id: "A2_L1",
      title_he: "עבר כבר קרה: passé composé",
      title_en: "Past tense: passé composé",
      title_fr: "Le passé composé",
      theory_he: "הpassé composé מבטא פעולות שהסתיימו בעבר. בונים אותו עם avoir או être + participe passé. רוב הפעלים משתמשים ב-avoir; פעלי תנועה ו-être משתמשים ב-être (ויש להתאים מין ומספר).",
      theory_en: "The passé composé expresses completed past actions. It is built with avoir or être + past participle. Most verbs use avoir; motion verbs and reflexives use être (and must agree in gender and number).",
      grammar: {
        headers: ["Auxiliaire", "Participe passé", "Exemple"],
        rows: [
          ["avoir", "mangé (manger)", "J'ai mangé une pomme."],
          ["avoir", "parlé (parler)", "Tu as parlé vite."],
          ["avoir", "fini (finir)", "Il a fini le livre."],
          ["être", "allé(e) (aller)", "Elle est allée au marché."],
          ["être", "parti(e) (partir)", "Nous sommes partis tôt."],
          ["être", "arrivé(e) (arriver)", "Ils sont arrivés hier."],
        ],
      },
      vocab: [
        { fr: "j'ai mangé", he: "אכלתי", en: "I ate" },
        { fr: "tu as parlé", he: "דיברת", en: "you spoke" },
        { fr: "il est allé", he: "הוא הלך", en: "he went" },
        { fr: "elle est venue", he: "היא באה", en: "she came" },
        { fr: "nous avons vu", he: "ראינו", en: "we saw" },
        { fr: "ils ont fait", he: "הם עשו", en: "they did/made" },
      ],
      examples: [
        { fr: "J'ai mangé une pizza hier.", he: "אכלתי פיצה אתמול.", en: "I ate a pizza yesterday." },
        { fr: "Elle est allée en France.", he: "היא נסעה לצרפת.", en: "She went to France." },
        { fr: "Nous avons vu un film.", he: "ראינו סרט.", en: "We watched a film." },
        { fr: "Ils sont arrivés à l'heure.", he: "הם הגיעו בזמן.", en: "They arrived on time." },
      ],
      video: "mpeHI3zbPWk",
      images: [
        {
          url: "https://images.unsplash.com/photo-1544027026-31fbbad5ecee?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "ארוחת בוקר בפריז — j'ai mangé un croissant",
          caption_en: "Parisian breakfast — j'ai mangé un croissant",
          type: "illustration",
        },
      ],
    },
    {
      id: "A2_L2",
      title_he: "עתיד קרוב: futur proche",
      title_en: "Near future: futur proche",
      title_fr: "Le futur proche",
      theory_he: "הfutur proche מבטא כוונה או פעולה עתידית קרובה. בונים אותו עם aller בהווה + infinitif. זו צורת העתיד הנפוצה ביותר בשפה המדוברת.",
      theory_en: "The futur proche expresses an intention or near-future action. It is built with aller in the present + infinitive. This is the most common future form in spoken French.",
      grammar: {
        headers: ["Sujet", "aller (présent)", "+ infinitif", "Exemple"],
        rows: [
          ["je", "vais", "partir", "Je vais partir demain."],
          ["tu", "vas", "manger", "Tu vas manger quoi ?"],
          ["il/elle", "va", "appeler", "Elle va appeler."],
          ["nous", "allons", "voyager", "Nous allons voyager."],
          ["vous", "allez", "travailler", "Vous allez travailler ?"],
          ["ils/elles", "vont", "arriver", "Ils vont arriver bientôt."],
        ],
      },
      vocab: [
        { fr: "bientôt", he: "בקרוב", en: "soon" },
        { fr: "demain", he: "מחר", en: "tomorrow" },
        { fr: "ce soir", he: "הערב", en: "this evening" },
        { fr: "la semaine prochaine", he: "שבוע הבא", en: "next week" },
        { fr: "tout à l'heure", he: "עוד מעט", en: "in a little while" },
      ],
      examples: [
        { fr: "Je vais partir demain.", he: "אני הולך לעזוב מחר.", en: "I am going to leave tomorrow." },
        { fr: "Elle va appeler ce soir.", he: "היא הולכת להתקשר הערב.", en: "She is going to call this evening." },
        { fr: "Nous allons manger ensemble.", he: "אנחנו הולכים לאכול ביחד.", en: "We are going to eat together." },
        { fr: "Ils vont bientôt arriver.", he: "הם הולכים להגיע בקרוב.", en: "They are going to arrive soon." },
      ],
      video: "UlW3OHHkD5I",
      images: [
        {
          url: "https://images.unsplash.com/photo-1755090249373-dfbf3a462f6c?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "כרם הענבים — je vais voyager en France",
          caption_en: "French vineyard — je vais voyager en France",
          type: "illustration",
        },
      ],
    },
    {
      id: "A2_L3",
      title_he: "תארים ותיאום: accord des adjectifs",
      title_en: "Adjective agreement",
      title_fr: "L'accord des adjectifs",
      theory_he: "בצרפתית, תואר השם חייב להסכים עם השם במין ובמספר. לנקבה מוסיפים -e, לרבים -s, ולנקבה רבים -es. לתארים מסוימים יש צורות לא סדירות.",
      theory_en: "In French, adjectives must agree with the noun in gender and number. Add -e for feminine, -s for plural, -es for feminine plural. Some adjectives have irregular forms.",
      grammar: {
        headers: ["Masculin sing.", "Féminin sing.", "Masculin pl.", "Féminin pl."],
        rows: [
          ["grand", "grande", "grands", "grandes"],
          ["petit", "petite", "petits", "petites"],
          ["beau", "belle", "beaux", "belles"],
          ["nouveau", "nouvelle", "nouveaux", "nouvelles"],
          ["heureux", "heureuse", "heureux", "heureuses"],
          ["sportif", "sportive", "sportifs", "sportives"],
        ],
      },
      vocab: [
        { fr: "grand(e)", he: "גדול/ה", en: "big/tall" },
        { fr: "petit(e)", he: "קטן/ה", en: "small" },
        { fr: "beau / belle", he: "יפה", en: "beautiful" },
        { fr: "heureux / heureuse", he: "שמח/ה", en: "happy" },
        { fr: "intelligent(e)", he: "חכם/ה", en: "intelligent" },
        { fr: "sympa(thique)", he: "נחמד/ה", en: "nice" },
      ],
      examples: [
        { fr: "Un grand appartement.", he: "דירה גדולה.", en: "A big apartment." },
        { fr: "Une belle ville.", he: "עיר יפה.", en: "A beautiful city." },
        { fr: "Des amis sympas.", he: "חברים נחמדים.", en: "Nice friends." },
        { fr: "Elle est très intelligente.", he: "היא מאוד חכמה.", en: "She is very intelligent." },
      ],
      video: "G7Z2ya6Ov-M",
      images: [
        {
          url: "https://images.unsplash.com/photo-1520939817895-060bdaf4fe1b?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "un bon croissant chaud — תואר מסכים עם השם",
          caption_en: "un bon croissant chaud — adjective agrees with the noun",
          type: "illustration",
        },
      ],
    },
    {
      id: "A2_L4",
      title_he: "מילות קישור",
      title_en: "Linking words",
      title_fr: "Les connecteurs logiques",
      theory_he: "מילות קישור מחברות רעיונות ומשפרות את הזרימה של הטקסט. הן חיוניות לשיחה ולכתיבה ברמה A2 ומעלה.",
      theory_en: "Linking words connect ideas and improve the flow of text. They are essential for conversation and writing at A2 level and above.",
      grammar: {
        headers: ["Connecteur", "Fonction", "Exemple"],
        rows: [
          ["et", "הוספה", "J'aime le café et le thé."],
          ["mais", "ניגוד", "Je veux venir, mais je suis fatigué."],
          ["donc", "מסקנה", "Il pleut, donc je reste à la maison."],
          ["parce que", "סיבה", "Je suis content parce que j'ai réussi."],
          ["alors", "אז/כתוצאה", "Je n'avais pas faim, alors je n'ai pas mangé."],
          ["pourtant", "למרות זאת", "Il est tard, pourtant il continue."],
        ],
      },
      vocab: [
        { fr: "et", he: "ו / וגם", en: "and" },
        { fr: "mais", he: "אבל", en: "but" },
        { fr: "donc", he: "לכן / אז", en: "so / therefore" },
        { fr: "parce que", he: "כי / מכיוון ש", en: "because" },
        { fr: "alors", he: "אז / לכן", en: "then / so" },
        { fr: "pourtant", he: "למרות זאת", en: "yet / however" },
        { fr: "enfin", he: "סוף סוף / לבסוף", en: "finally" },
      ],
      examples: [
        { fr: "J'aime le café, mais je préfère le thé.", he: "אני אוהב קפה, אבל אני מעדיף תה.", en: "I like coffee, but I prefer tea." },
        { fr: "Je suis fatigué parce que j'ai travaillé toute la journée.", he: "אני עייף כי עבדתי כל היום.", en: "I'm tired because I worked all day." },
        { fr: "Il pleut, donc je reste chez moi.", he: "יורד גשם, לכן אני נשאר בבית.", en: "It's raining, so I'm staying home." },
        { fr: "C'est cher, pourtant les gens achètent.", he: "זה יקר, למרות זאת אנשים קונים.", en: "It's expensive, yet people buy it." },
      ],
      video: "y8CKi4Q_SdA",
      images: [
        {
          url: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "ספרים — מילות קישור מחברות רעיונות",
          caption_en: "Books — linking words connect ideas",
          type: "illustration",
        },
      ],
    },
    {
      id: "A2_L5",
      title_he: "ביטויי זמן בעבר",
      title_en: "Past time expressions",
      title_fr: "Les expressions de temps au passé",
      theory_he: "ביטויי זמן עוזרים לעגן את הסיפור בציר הזמן. בשימוש עם passé composé, הם מגלים מתי בדיוק התרחשה הפעולה.",
      theory_en: "Time expressions anchor the story in time. When used with the passé composé, they reveal exactly when the action occurred.",
      grammar: {
        headers: ["Expression", "משמעות", "Exemple"],
        rows: [
          ["hier", "אתמול", "J'ai appelé hier."],
          ["avant-hier", "שלשום", "Elle est venue avant-hier."],
          ["la semaine dernière", "שבוע שעבר", "Nous avons voyagé la semaine dernière."],
          ["il y a + temps", "לפני...", "Il y a deux jours, j'ai vu ce film."],
          ["le mois dernier", "חודש שעבר", "Il a déménagé le mois dernier."],
          ["l'année dernière", "שנה שעברה", "Ils se sont rencontrés l'année dernière."],
        ],
      },
      vocab: [
        { fr: "hier", he: "אתמול", en: "yesterday" },
        { fr: "avant-hier", he: "שלשום", en: "the day before yesterday" },
        { fr: "il y a deux jours", he: "לפני יומיים", en: "two days ago" },
        { fr: "la semaine dernière", he: "שבוע שעבר", en: "last week" },
        { fr: "le mois dernier", he: "חודש שעבר", en: "last month" },
        { fr: "l'année dernière", he: "שנה שעברה", en: "last year" },
      ],
      examples: [
        { fr: "Hier, j'ai mangé une bonne pizza.", he: "אתמול אכלתי פיצה טובה.", en: "Yesterday I ate a good pizza." },
        { fr: "Il y a trois jours, elle a appelé.", he: "לפני שלושה ימים, היא התקשרה.", en: "Three days ago, she called." },
        { fr: "La semaine dernière, nous avons vu un film.", he: "שבוע שעבר ראינו סרט.", en: "Last week we watched a film." },
        { fr: "L'année dernière, ils ont voyagé en Italie.", he: "שנה שעברה הם נסעו לאיטליה.", en: "Last year, they traveled to Italy." },
      ],
      video: "yrL2nPF83no",
      images: [
        {
          url: "https://images.unsplash.com/photo-1578590550634-53ccf6d6cf04?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "הדגל הצרפתי — היסטוריה ועבר",
          caption_en: "The French flag — history and the past",
          type: "illustration",
        },
      ],
    },
    {
      id: "A2_L6",
      title_he: "השוואת דברים",
      title_en: "Making comparisons",
      title_fr: "La comparaison",
      theory_he: "השוואה בצרפתית: plus...que (יותר מ), moins...que (פחות מ), aussi...que (כמו). לניתוח מושלם יש גם superlatives: le plus / le moins.",
      theory_en: "Comparison in French: plus...que (more than), moins...que (less than), aussi...que (as...as). For the superlative: le plus / le moins.",
      grammar: {
        headers: ["Type", "Structure", "Exemple"],
        rows: [
          ["Supériorité", "plus + adj + que", "Paris est plus grande que Lyon."],
          ["Infériorité", "moins + adj + que", "Ce café est moins cher que l'autre."],
          ["Égalité", "aussi + adj + que", "Elle est aussi sympa que lui."],
          ["Superlatif +", "le/la/les plus + adj", "C'est la ville la plus belle."],
          ["Superlatif −", "le/la/les moins + adj", "C'est le moins cher."],
        ],
      },
      vocab: [
        { fr: "plus … que", he: "יותר … מ", en: "more … than" },
        { fr: "moins … que", he: "פחות … מ", en: "less … than" },
        { fr: "aussi … que", he: "כמו", en: "as … as" },
        { fr: "le plus", he: "הכי", en: "the most" },
        { fr: "le moins", he: "הכי פחות", en: "the least" },
        { fr: "meilleur(e)", he: "טוב יותר", en: "better" },
        { fr: "le/la meilleur(e)", he: "הטוב/הטובה ביותר", en: "the best" },
      ],
      examples: [
        { fr: "Paris est plus grande que Lyon.", he: "פריז גדולה יותר מליון.", en: "Paris is bigger than Lyon." },
        { fr: "Ce vin est moins cher que l'autre.", he: "היין הזה פחות יקר מהאחר.", en: "This wine is less expensive than the other." },
        { fr: "Elle court aussi vite que lui.", he: "היא רצה מהר כמוהו.", en: "She runs as fast as he does." },
        { fr: "C'est le meilleur restaurant de la ville.", he: "זה המסעדה הטובה ביותר בעיר.", en: "It's the best restaurant in the city." },
      ],
      video: "Ne431tdamsk",
      images: [
        {
          url: "https://images.unsplash.com/photo-1650461460131-6f4275899270?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "פריז מלמעלה — la plus grande ville du monde?",
          caption_en: "Paris from above — la plus grande ville du monde?",
          type: "illustration",
        },
      ],
    },
  ],

  B1: [
    {
      id: "B1_L1",
      title_he: "עבר מתמשך: imparfait",
      title_en: "Imperfect tense: imparfait",
      title_fr: "L'imparfait",
      theory_he: "ה-imparfait מתאר פעולות מתמשכות, הרגלים, ומצבים בעבר. בשונה מpassé composé שמתאר פעולות שהסתיימו, ה-imparfait מתאר 'רקע' או מצב.",
      theory_en: "The imparfait describes ongoing actions, habits, and states in the past. Unlike the passé composé which describes completed actions, the imparfait describes 'background' or states.",
      grammar: {
        headers: ["Pronom", "parler (imparfait)", "Exemple"],
        rows: [
          ["je", "parlais", "Je parlais français quand j'étais enfant."],
          ["tu", "parlais", "Tu habitais à Paris ?"],
          ["il/elle", "parlait", "Elle travaillait tous les jours."],
          ["nous", "parlions", "Nous mangions ensemble le soir."],
          ["vous", "parliez", "Vous voyagiez souvent ?"],
          ["ils/elles", "parlaient", "Ils lisaient beaucoup."],
        ],
      },
      vocab: [
        { fr: "quand j'étais enfant", he: "כשהייתי ילד", en: "when I was a child" },
        { fr: "tous les jours", he: "כל יום", en: "every day" },
        { fr: "souvent", he: "לעיתים קרובות", en: "often" },
        { fr: "autrefois", he: "בעבר / פעם", en: "in the past / formerly" },
        { fr: "d'habitude", he: "בדרך כלל", en: "usually" },
      ],
      examples: [
        { fr: "Quand j'étais enfant, je jouais au football.", he: "כשהייתי ילד, שיחקתי כדורגל.", en: "When I was a child, I used to play football." },
        { fr: "Il faisait beau et les enfants jouaient dehors.", he: "היה יפה והילדים שיחקו בחוץ.", en: "The weather was nice and the children were playing outside." },
        { fr: "D'habitude, elle prenait le bus.", he: "בדרך כלל היא נסעה באוטובוס.", en: "Usually she took the bus." },
      ],
      video: "CFSZqYHqnvA",
      images: [
        {
          url: "https://images.unsplash.com/photo-1761322572550-967ea8c0bfd9?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "יומן ישן — autrefois, je parlais, j'habitais...",
          caption_en: "Old journal — autrefois, je parlais, j'habitais...",
          type: "illustration",
        },
      ],
    },
    {
      id: "B1_L2",
      title_he: "ביטוי דעות",
      title_en: "Expressing opinions",
      title_fr: "Exprimer son opinion",
      theory_he: "בצרפתית רשמית ומדוברת כאחד, חשוב לדעת לבטא דעה, להסכים, ולחלוק. שימוש במבנים כמו 'Je pense que', 'À mon avis', 'Il me semble que' מגביר את רמת הצרפתית שלך.",
      theory_en: "In both formal and spoken French, it is important to express opinions, agree, and disagree. Using structures like 'Je pense que', 'À mon avis', 'Il me semble que' raises your French level.",
      grammar: {
        headers: ["Expression", "Usage", "Exemple"],
        rows: [
          ["Je pense que + indic.", "דעה כללית", "Je pense que c'est une bonne idée."],
          ["Je crois que + indic.", "אמונה / דעה", "Je crois qu'il a raison."],
          ["À mon avis,", "לדעתי", "À mon avis, c'est trop cher."],
          ["Il me semble que + indic.", "נדמה לי", "Il me semble que tu te trompes."],
          ["Je trouve que + indic.", "אני מוצא ש", "Je trouve que c'est injuste."],
        ],
      },
      vocab: [
        { fr: "Je pense que...", he: "אני חושב ש...", en: "I think that..." },
        { fr: "À mon avis", he: "לדעתי", en: "In my opinion" },
        { fr: "Je suis d'accord", he: "אני מסכים", en: "I agree" },
        { fr: "Je ne suis pas d'accord", he: "אני לא מסכים", en: "I disagree" },
        { fr: "Absolument", he: "בהחלט", en: "Absolutely" },
        { fr: "Pas du tout", he: "בכלל לא", en: "Not at all" },
      ],
      examples: [
        { fr: "Je pense que c'est une excellente idée.", he: "אני חושב שזו רעיון מצוין.", en: "I think it's an excellent idea." },
        { fr: "À mon avis, il faut agir maintenant.", he: "לדעתי, צריך לפעול עכשיו.", en: "In my opinion, we need to act now." },
        { fr: "Je suis tout à fait d'accord avec vous.", he: "אני לגמרי מסכים אתכם.", en: "I completely agree with you." },
      ],
      video: "Wh5hHrtme5I",
      images: [
        {
          url: "https://images.unsplash.com/photo-1779358296802-715fc9fbc152?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "דיון בצרפתית — à mon avis, je pense que...",
          caption_en: "Discussion in French — à mon avis, je pense que...",
          type: "illustration",
        },
      ],
    },
    {
      id: "B1_L3",
      title_he: "בקרוב — שיעורים נוספים",
      title_en: "More lessons coming soon",
      title_fr: "Bientôt disponible",
      theory_he: "שיעורים נוספים לרמה B1 יתווספו בקרוב! נושאים: subjonctif, pronoms relatifs, conditionnel ועוד.",
      theory_en: "More B1 lessons are coming soon! Topics: subjonctif, pronoms relatifs, conditionnel and more.",
      grammar: null,
      vocab: [],
      examples: [],
      comingSoon: true,
      video: null,
      images: [],
    },
  ],

  B2: [
    {
      id: "B2_L1",
      title_he: "ה-subjonctif — אופן הספק",
      title_en: "The subjunctive mood",
      title_fr: "Le subjonctif",
      theory_he: "הsubjonctif משמש לביטוי ספק, רצון, רגש, או הכרח. הוא מגיע לרוב אחרי 'que' בצורה 'il faut que', 'je veux que', 'bien que' וכד'.",
      theory_en: "The subjunctive is used to express doubt, desire, emotion, or necessity. It usually follows 'que' in structures like 'il faut que', 'je veux que', 'bien que', etc.",
      grammar: {
        headers: ["Pronom", "être (subjonctif)", "avoir (subjonctif)"],
        rows: [
          ["que je", "sois", "aie"],
          ["que tu", "sois", "aies"],
          ["qu'il/elle", "soit", "ait"],
          ["que nous", "soyons", "ayons"],
          ["que vous", "soyez", "ayez"],
          ["qu'ils/elles", "soient", "aient"],
        ],
      },
      vocab: [
        { fr: "il faut que + subj.", he: "צריך ש...", en: "it is necessary that..." },
        { fr: "je veux que + subj.", he: "אני רוצה ש...", en: "I want (you/them) to..." },
        { fr: "bien que + subj.", he: "אף על פי ש...", en: "although..." },
        { fr: "pour que + subj.", he: "כדי ש...", en: "so that..." },
        { fr: "avant que + subj.", he: "לפני ש...", en: "before..." },
      ],
      examples: [
        { fr: "Il faut que tu sois là à huit heures.", he: "אתה צריך להיות שם בשמונה.", en: "You need to be there at eight." },
        { fr: "Je veux qu'il vienne avec nous.", he: "אני רוצה שהוא יבוא אתנו.", en: "I want him to come with us." },
        { fr: "Bien qu'il soit fatigué, il continue.", he: "אף על פי שהוא עייף, הוא ממשיך.", en: "Although he is tired, he continues." },
      ],
      video: "94tjCnc9l0E",
      images: [
        {
          url: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&q=80&auto=format&fit=crop&h=220",
          caption_he: "פריז בלילה — il faut que tu sois là",
          caption_en: "Paris at night — il faut que tu sois là",
          type: "illustration",
        },
      ],
    },
    {
      id: "B2_L2",
      title_he: "בקרוב — שיעורים נוספים",
      title_en: "More lessons coming soon",
      title_fr: "Bientôt disponible",
      theory_he: "שיעורים נוספים לרמה B2 יתווספו בקרוב!",
      theory_en: "More B2 lessons are coming soon!",
      grammar: null,
      vocab: [],
      examples: [],
      comingSoon: true,
      video: null,
      images: [],
    },
  ],

  C1: [
    {
      id: "C1_L1",
      title_he: "סגנון גבוה ומשלבים",
      title_en: "High register and stylistic levels",
      title_fr: "Le registre soutenu",
      theory_he: "בצרפתית קיימים שלושה משלבים עיקריים: familier (דיבור יומיומי), courant (סטנדרטי), וsoutenu (גבוה/כתוב). ברמה C1 חשוב לשלוט בכולם.",
      theory_en: "French has three main register levels: familier (casual speech), courant (standard), and soutenu (formal/written). At C1 level it is important to master all three.",
      grammar: {
        headers: ["Familier", "Courant", "Soutenu"],
        rows: [
          ["C'est pas bien.", "Ce n'est pas bien.", "Cela n'est guère satisfaisant."],
          ["J'veux pas.", "Je ne veux pas.", "Je refuse catégoriquement."],
          ["T'as vu ?", "Tu as vu ?", "Avez-vous remarqué ?"],
          ["Y'a pas de problème.", "Il n'y a pas de problème.", "Il n'y a pas lieu de s'inquiéter."],
        ],
      },
      vocab: [
        { fr: "néanmoins", he: "עם זאת", en: "nevertheless" },
        { fr: "cependant", he: "למרות זאת", en: "however" },
        { fr: "en outre", he: "בנוסף לכך", en: "furthermore" },
        { fr: "par conséquent", he: "כתוצאה מכך", en: "consequently" },
        { fr: "il convient de", he: "ראוי / נכון ל-", en: "it is appropriate to" },
      ],
      examples: [
        { fr: "Néanmoins, cette approche présente des lacunes.", he: "עם זאת, לגישה זו יש פערים.", en: "Nevertheless, this approach has gaps." },
        { fr: "Par conséquent, une révision s'impose.", he: "כתוצאה מכך, נדרשת עדכון.", en: "Consequently, a revision is needed." },
        { fr: "Il convient de souligner ce point.", he: "ראוי להדגיש נקודה זו.", en: "It is appropriate to emphasize this point." },
      ],
      video: null,
      images: [],
    },
    {
      id: "C1_L2",
      title_he: "בקרוב — שיעורים נוספים",
      title_en: "More lessons coming soon",
      title_fr: "Bientôt disponible",
      theory_he: "שיעורים נוספים לרמה C1 יתווספו בקרוב!",
      theory_en: "More C1 lessons are coming soon!",
      grammar: null,
      vocab: [],
      examples: [],
      comingSoon: true,
      video: null,
      images: [],
    },
  ],

  C2: [
    {
      id: "C2_L1",
      title_he: "ניואנסים ומטפורות",
      title_en: "Nuance and metaphor",
      title_fr: "Nuances et métaphores",
      theory_he: "ברמה C2, הצרפתית שלך אמורה לשקף עושר סגנוני: שימוש במטפורות, אירוניה, ומבנים מורכבים שמאפיינים את הכתיבה הספרותית והאקדמית הגבוהה.",
      theory_en: "At C2 level, your French should reflect stylistic richness: use of metaphors, irony, and complex structures that characterize high literary and academic writing.",
      grammar: {
        headers: ["Procédé stylistique", "Définition", "Exemple"],
        rows: [
          ["Métaphore", "השוואה ישירה ללא 'כמו'", "La vie est un voyage."],
          ["Antithèse", "ניגוד בין שתי רעיונות", "Il faut manger pour vivre, non vivre pour manger."],
          ["Litote", "אמירת פחות ממה שמתכוונים", "Ce n'est pas mal. (= c'est très bien)"],
          ["Euphémisme", "ריכוך של אמירה קשה", "Il a disparu. (= il est mort)"],
          ["Périphrase", "תיאור עקיף", "la Ville Lumière (= Paris)"],
        ],
      },
      vocab: [
        { fr: "à juste titre", he: "בצדק", en: "rightly so" },
        { fr: "force est de constater", he: "אי אפשר שלא להבחין", en: "one cannot deny" },
        { fr: "au demeurant", he: "בשאר העניינים", en: "for the rest" },
        { fr: "nonobstant", he: "על אף", en: "notwithstanding" },
        { fr: "eu égard à", he: "בהתחשב ב-", en: "with regard to" },
      ],
      examples: [
        { fr: "Force est de constater que la situation s'est dégradée.", he: "אי אפשר שלא להבחין שהמצב הידרדר.", en: "One cannot deny that the situation has deteriorated." },
        { fr: "Au demeurant, ses arguments restent pertinents.", he: "בשאר העניינים, טיעוניו עדיין רלוונטיים.", en: "For the rest, his arguments remain relevant." },
        { fr: "La vie est un long fleuve tranquille.", he: "החיים הם נהר ארוך ושקט.", en: "Life is a long quiet river (a well-known French metaphor)." },
      ],
      video: null,
      images: [],
    },
    {
      id: "C2_L2",
      title_he: "בקרוב — שיעורים נוספים",
      title_en: "More lessons coming soon",
      title_fr: "Bientôt disponible",
      theory_he: "שיעורים נוספים לרמה C2 יתווספו בקרוב!",
      theory_en: "More C2 lessons are coming soon!",
      grammar: null,
      vocab: [],
      examples: [],
      comingSoon: true,
      video: null,
      images: [],
    },
  ],
};

export default LESSONS;
